/** Declaration file generated by dts-gen */

export function Input(mensagem: any): any;

export function InputCheck(mensagem: any, escolhas: any): any;

export function InputConfirm(mensagem: any): any;

export function InputEditor(mensagem: any): any;

export function InputExpand(mensagem: any, escolhas: any): any;

export function InputList(mensagem: any, escolhas: any): any;

export function InputNumber(mensagem: any): any;

export function InputPass(mensagem: any): any;

export function InputRaw(mensagem: any, escolhas: any): any;

export function InputTable(mensagem: any, colunas: any, linhas: any): any;

export function Print(titulo: any, linhas: any): void;

export function PrintCustom(titulo: any, cor: any, linhas: any): void;

export function PrintError(titulo: any, linhas: any): void;

export function PrintOk(titulo: any, linhas: any): void;

export function VerifyParams(Params: any, Ex: any): any;

